# -*- coding: utf-8 -*-
"""
/***************************************************************************
 NdViDialog
                                 A QGIS plugin
 NDVI
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2023-10-15
        git sha              : $Format:%H$
        copyright            : (C) 2023 by Yann CHEMIN
        email                : dr.yann.chemin@gmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 * This is free and unencumbered software released into the public domain. *
 *  Anyone is free to copy, modify, publish, use, compile, sell, or        *
 *  distribute this software, either in source code form or as a compiled  *
 *  binary, for any purpose, commercial or non-commercial, and by any      *
 *  means.                                                                 * 
 *  In jurisdictions that recognize copyright laws, the author or authors  *
 *  of this software dedicate any and all copyright interest in the        *
 *  software to the public domain. We make this dedication for the benefit *
 *  of the public at large and to the detriment of our heirs and           *
 *  successors. We intend this dedication to be an overt act of            *
 *  relinquishment in perpetuity of all present and future rights to this  *
 *  software under copyright law.                                          *
 *  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,        *
 *  EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF     *
 *  MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. *
 *  IN NO EVENT SHALL THE AUTHORS BE LIABLE FOR ANY CLAIM, DAMAGES OR      *
 *  OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,  *
 *  ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR  *
 *  OTHER DEALINGS IN THE SOFTWARE.                                        *
 *  For more information, please refer to <http://unlicense.org/>          *
 *                                                                         *
 ***************************************************************************/
"""

import os

from qgis.PyQt import uic
from qgis.PyQt import QtWidgets

# This loads your .ui file so that PyQt can populate your plugin with the elements from Qt Designer
FORM_CLASS, _ = uic.loadUiType(os.path.join(
    os.path.dirname(__file__), 'ndvi_dialog_base.ui'))


class NdViDialog(QtWidgets.QDialog, FORM_CLASS):
    def __init__(self, parent=None):
        """Constructor."""
        super(NdViDialog, self).__init__(parent)
        # Set up the user interface from Designer through FORM_CLASS.
        # After self.setupUi() you can access any designer object by doing
        # self.<objectname>, and you can use autoconnect slots - see
        # http://qt-project.org/doc/qt-4.8/designer-using-a-ui-file.html
        # #widgets-and-dialogs-with-auto-connect
        self.setupUi(self)
